; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[platformio]
default_envs = lolin_s3_zero
src_dir = firmware/src
lib_dir = firmware/lib
include_dir = firmware/include
data_dir = build/littlefs

[common]
board_build.embed_files = 
	images/logo.jpg
	
	images/weather/light/moonCloudW.jpg
	images/weather/light/sunCloudsW.jpg
	images/weather/light/sunW.jpg
	images/weather/light/moonW.jpg
	images/weather/light/snowW.jpg
	images/weather/light/rainW.jpg
	images/weather/light/cloudsW.jpg
	images/weather/dark/moonCloudB.jpg
	images/weather/dark/sunCloudsB.jpg
	images/weather/dark/sunB.jpg
	images/weather/dark/moonB.jpg
	images/weather/dark/snowB.jpg
	images/weather/dark/rainB.jpg
	images/weather/dark/cloudsB.jpg
	
	fonts/RobotoRegular.ttf
	fonts/FinalFrontier.ttf
	
	fonts/DSEG7ClassicBold.ttf
	fonts/DSEG14ClassicBold.ttf
;	fonts/DSEG7ModernBold.ttf
;	fonts/DSEG14ModernBold.ttf
board_build.filesystem = littlefs
framework = arduino
lib_deps = 
	SPI
	FS
	SPIFFS
	LittleFS
	SD
	bblanchon/ArduinoJson@^7.0.4
	bblanchon/StreamUtils@^1.9.0
	bodmer/TFT_eSPI@^2.5.43
	bodmer/TJpg_Decoder@^1.1.0
	knolleary/PubSubClient@^2.8
	tzapu/WiFiManager@^2.0.17
	thijse/ArduinoLog@^1.1.1
	adafruit/Adafruit NeoPixel@^1.15.4
	fbiego/ESP32Time@^2.0.6
monitor_speed = 115200
extra_scripts = 
	pre:scripts/generate_git_info.py
	pre:scripts/embed_files.py
	pre:scripts/copy_files_to_littlefs.py
	pre:scripts/upload_littlefs.py
build_flags = 
	-D DISABLE_ALL_LIBRARY_WARNINGS
	-D USER_SETUP_LOADED=1
	-Wfatal-errors
	-I firmware/config
	-I firmware/src/core/autodimming
	-I firmware/src/core/button
	-I firmware/src/core/configmanager
	-I firmware/src/core/globaltime
	-I firmware/src/core/i18n
	-I firmware/src/core/screenmanager
	-I firmware/src/core/utils
	-I firmware/src/core/widget
	-I firmware/src/widgets
	-include "firmware/config/config_helper.h"
;	-D WM_DEBUG_LEVEL=WM_DEBUG_DEV

[env:lolin_s3_zero]
platform = espressif32@6.6.0
board = lolin_s3_mini
board_build.partitions = partitions.csv
extends = common
build_flags = 
	${common.build_flags}
	-D PCB_VERSION="\"infoorbs-npc\""
	-D USE_HSPI_PORT
	-D TFT_MOSI=4
;	-D TFT_MISO=-1
	-D TFT_SCLK=5
	-D TFT_CS=15
	-D TFT_DC=3
	-D TFT_RST=2
	-D SCREEN_1_CS=6
	-D SCREEN_2_CS=7
	-D SCREEN_3_CS=8
	-D SCREEN_4_CS=9
	-D SCREEN_5_CS=10
	-D BUTTON_LEFT_PIN=1
	-D BUTTON_MIDDLE_PIN=12
	-D BUTTON_RIGHT_PIN=11
	-D BUTTON_MODE=INPUT_PULLUP
	-D BUSY_PIN=21
	-D LED_TYPE=1
	-D LED_COLOR=0x001F
	-D LIGHT_SENSE_PIN=13
	-D SPI_FREQUENCY=40000000
	-D ARDUINO_USB_CDC_ON_BOOT=1
	-D TFT_SDA_READ=1
	-D BOARD_HAS_PSRAM
	-mfix-esp32-psram-cache-issue
;	-D MEMORY_DEBUG_INTERVAL 5000
;	-D CM_DEBUG
;	-D ZONE_DEBUG
;	-D GT_DEBUG
;	-D STOCK_DEBUG
;	-D TASK_DEBUG
;	-D TASKMANAGER_DEBUG
;	-D PR_DEBUG
